version: '3.8'

services:
  latex-compiler:
    build: .
    container_name: latex-compiler-prod
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - API_KEY=djsakjc213hjbkk3h123jkb123kbj
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - /tmp:/tmp
      - gunicorn_logs:/var/log/gunicorn
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-API-KEY: djsakjc213hjbkk3h123jkb123kbj", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID

volumes:
  gunicorn_logs:
